[build]
  command = "npm run build"
  publish = "dist/public"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api.cjs/:splat"
  status = 200

[[redirects]]
  from = "/api/audio/*"
  to = "/.netlify/functions/audio.cjs/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200